* Automated research processing
With suppress, you can make processing and extracting data from user responses much easier.
+ Why? :: Although a direct survey is a great way to collect quantitative data, qualitative data might provide much more insight. With suppress, you can easily extract qualitative data from user responses and process it in a way that is easy to understand and analyze, without losing the ability to collect quantitative data.

+ Example :: [[./demos/research/README.org][Financial literacy research]]

* Automating customer service
Use Suppress to automate customer service inquiries and provide speedy responses to customers. Automatically categorize inquiries, route them to the right department, and offer personalized advice to customers.

* Automated content generation
Use Suppress to generate high-quality content for your website, presentation, blog or article.

+ Example :: [[./demos/content_generation/README.org][Automated content generation]]


* Automated sentiment analysis
Use Suppress to analyze customer feedback and reviews. Automatically detect and measure sentiment in text, helping you to better understand customer opinions and drive better decision making.
* Automated natural language processing
Use Suppress to provide natural language processing capabilities in your applications. Automatically process text to extract entities, relationships, and more, helping you to gain valuable insights.
* Automated data analysis
Use Suppress to perform complex data analysis tasks. Automatically extract insights from data and deliver valuable information to users.

* Used By
+ https://feedme.streamlit.app/ This was a proof of concept to see how the underlying architecture of suppress.js could be used to quickly create something.
+ https://replit.com/@velocitatem/suppressjs?v=1 An implementation of Suppress.js to create a report on some historical event. Uses HTML to as a data fromat.
+ https://gitlab.com/-/snippets/2489814 This is a demo of how to use Suppress.js to create a simple backend.
