#+title: Suppress.js
#+description: Node.js Backend framework using AI.

# shield for


*Are you looking for a way to easily integrate complex AI features into your applications?*

Look no further than Suppress! Suppress is a node.js framework that makes it easy to add powerful features to your app with just a few lines of code. It is built on top of Express.js and uses AI to make your life easier.
With Suppress, you can quickly and easily add features and *take your app to the next level!*

Here is an [[https://www.linkedin.com/pulse/backend-ai-daniel-rosel][article]] demonstrating the power of suppress.js.

* Get Started
1. =npm i ai.suppress.js=
2. Create a file named =server.js= and add the following code:
    #+BEGIN_SRC javascript
      const {SuppressLLM , DataGenerator, SuppresServer} = require('ai.suppress.js');
      const llm = new SuppressLLM("OPENAI_API_KEY");
      const server = new SuppresServer();

      server.createEndpoint(
          "/hello/:name/:country",
          "GET",
          new DataGenerator(
              "Greet {name}. Create a brief description of {country}, in which the user lives.",
              JSON.stringify({"greeting":"string", "description":"string"}),
              llm
              )
          );

      server.start();
    #+END_SRC
3. Run the server using =node server.js=
4. Open your browser and go to =http://localhost:3000/hello/John/China= [Replace with your name and country]


Learn more about Suppress.js in the DOCS [[./DOCS.org][here]].

* Using Suppress.js and AI Responsibly
+ Data bias :: Suppress.js uses AI to generate data. This means that the data generated by Suppress.js may be biased. It is important to understand that Suppress.js is not a replacement for human intelligence. It is a tool to help you create better applications. It is important to understand the data that Suppress.js generates and to use it responsibly.

* Used By
+ https://feedme.streamlit.app/ This was a proof of concept to see how the underlying architecture of suppress.js could be used to quickly create something.
+ https://gitlab.com/-/snippets/2489814 This is a demo of how to use Suppress.js to create a simple backend.
* Features
+ Currently only runs over the OpenAI API
+ Support for the following LLMs: /Open Ai/
+ Quick and easy to use
+ Easy to integrate into your app
+ Easy to add new features

* Roadmap
+ [ ] Completely Non-technical interface for creating a server.
+ [ ] Add support for other LLMs.
+ [ ] Improve documentation.
+ [ ] Add support for other languages.

* Contributing
Any contributions are welcome, feel free to send me an email at [[mailto:daniel@alves.world]] for any questions or concerns. Im always looking for new ideas and ways to improve the framework.
